name: Terraform Plan Tests

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform-plan-tests:
    name: Terraform Plan Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd

      - name: Terraform init
        run: terraform init -backend=false

      - name: Terraform validate
        run: terraform validate

      - name: Terraform test
        id: terraform-test
        uses: Home-Office-Digital/core-cloud-workflow-terraform-actions/actions/test@main
        with:
          working-directory: .
          test-directory: tests/plan
          sonar-host-url: ${{ secrets.SONAR_HOST_URL }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}